### ISSUE TITLE
user account

### ISSUE THREAD

**Issue by Zolske** [Zolske/salt-and-pepper-manager#10]
As a
**user**
*I can*
**log into my account**
*so that*
**I can manage my booking(s)**
---
**tasks**
- [x] create a database for the user which contains the password, username
- [x] create "sign up" form
- [x] create "log in" form 
- [x] create "log out" button
