### ISSUE TITLE
book table

### ISSUE THREAD

**Issue by Zolske** [Zolske/salt-and-pepper-manager#11]
As a
**user**
*I can*
**book a table**
*so that*
**I can plan ahead.**
---
**tasks**
- [x] create a database that contains all the table reservations
- [x] display the correct bookings only to the user who owns the booking
- [x] when he is logged in
- [x] on the booking page
