### ISSUE TITLE
amend booking

### ISSUE THREAD

**Issue by Zolske** [Zolske/salt-and-pepper-manager#13]
As a
**user**
*I can*
**amend my booking**
*so that*
**I can change the number of tables, the time, or the date.**
---
**tasks**
- *is not a "must have" because the user can just cancel a booking and make a new booking*
- [x] add a "amend" button next to each reservation, which sends a form to the database
- [x] implement JavaScript logic to avoid that the user can make a booking for a table, date, time that not exist
- [x] implement Python logic to update the database according to the form
