### ISSUE TITLE
customise user profile

### ISSUE THREAD

**Issue by Zolske** [Zolske/salt-and-pepper-manager#14]
As a
**user**
*I can*
**upload my profile picture**
*so that*
**my account feels more personal.**
---
**tasks**
- *is not a "must have" because it is not essential for booking a table*
- [x] add a page where the user can upload his/her profile picture
- [x] use the "Cloudinary" API so users can upload a profile picture
- [x] implement logic to save "profile picture cloudinary link" to user account
- [x] display correct user profile picture when user is logged in
