### ISSUE TITLE
update menu

### ISSUE THREAD

**Issue by Zolske** [Zolske/salt-and-pepper-manager#15]
As a
**owner**
*I can*
**update the restaurant's menu quick and easily**
*so that*
**I can stay flexible.**
---
**tasks**
- *is not a "must have", guests could still book a table without it*
- [x] create a database that holds the menu attributes
- [x] display the menu on the page
- [x] connect "menu" database to admin page so the owner can update menu
- [x] connect to Cloudinary so owner can upload menu images
