### ISSUE TITLE
user can write comments

### ISSUE THREAD

**Issue by Zolske** [Zolske/salt-and-pepper-manager#16]
As a
**user**
*I can*
**write a comment about the service of the restaurant**
*so that*
**the restaurant can improve on its service.**
---
**tasks**
- * is "could have" because guests could still book a table without it*
- [x] create a database for comments
- [x] create a page where the user can write a comment
- [x] display the comments (after they have been approved) on the landing page
- [x] save space by adding a carousel that scrolls through the comments
- [x] give the owner a chance to approve or remove comments on the admin page
